version: "3"
services:
  prototypekit-cr:
    build:
      context: .
    image: prototypekit-cr
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run start
