name: Dev deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ENVIRONMENT: infrastructure
  TIMEZONE: 'Europe/London'

jobs:
  # 1. Setup deployment variables
  setup:
    name: Setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.ENVIRONMENT }}
      timezone: ${{ env.TIMEZONE }}
    steps:
    - name: Environment 🧪
      run: echo "Environment set to ${{ env.ENVIRONMENT }}"

    - name: Timezone 🌐
      run: echo "Timezone set to ${{ env.TIMEZONE }}"

  build:
    name: Build and Deploy
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository 🗃️
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://crprototypekitdev001.azurecr.io/
          username: ${{ secrets.CAPROTOTYPEKITDEV001_REGISTRY_USERNAME }}
          password: ${{ secrets.CAPROTOTYPEKITDEV001_REGISTRY_PASSWORD }}

      - name: Build and push 📦️
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crprototypekitdev001.azurecr.io/prototype-kit-cr:${{ github.sha }}
          file: ./Dockerfile

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-prototypekit-cr-dev-001'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'crprototypekitdev001.azurecr.io/prototype-kit-cr:${{ github.sha }}'